#!/bin/sh
set -e
if command -v useradd >/dev/null 2>&1; then
	getent group hotserve >/dev/null 2>&1 || groupadd --system hotserve
	getent passwd hotserve >/dev/null 2>&1 || useradd --system \
		--gid hotserve --home-dir /var/lib/hotserve \
		--shell /usr/sbin/nologin --comment "hotserve server" hotserve
else
	# Alpine (busybox) fallback.
	addgroup -S hotserve 2>/dev/null || true
	adduser -S -G hotserve -h /var/lib/hotserve -s /sbin/nologin hotserve 2>/dev/null || true
fi
if ! uid=$(id -u hotserve 2>/dev/null); then
	echo "hotserve: the hotserve system user does not exist and could not be created" >&2
	exit 1
fi
# Best-effort: put the account IN the hotserve group. Both branches above
# set the group only when they create the account, so an account that
# already existed — an admin's, or one from another package — keeps
# whatever groups it had, and the state directories chowned below are
# group-hotserve. Not fatal: nothing the package installs is reachable
# only through the group.
in_group() { id -nG hotserve 2>/dev/null | tr ' ' '\n' | grep -qx hotserve; }
if ! in_group; then
	if command -v usermod >/dev/null 2>&1; then
		usermod -aG hotserve hotserve || true
	else
		addgroup hotserve hotserve 2>/dev/null || true # busybox
	fi
fi
if ! in_group; then
	echo "hotserve: the hotserve user is not a member of the hotserve group; add it with \`usermod -aG hotserve hotserve\` if its state directories become unreadable" >&2
fi
# /var/lib/hotserve-backup holds each app's staged database copies.
# It belongs to the hotserve user for the same reason the others do —
# the jobs write there — and because a restore onto a rebuilt box
# lands the database copies here before any job has run: root-owned,
# restic (as hotserve) could not create the directories and the
# documented recovery would stop halfway.
#
# Created here as well as shipped in the package, so this script can
# set a box up on its own: the e2e image runs it without installing
# the .deb, and a script that assumes its own payload cannot do that.
mkdir -p /var/lib/hotserve /var/lib/liveswap /var/lib/hotserve-backup
chmod 750 /var/lib/hotserve /var/lib/liveswap /var/lib/hotserve-backup
chown hotserve:hotserve /var/lib/hotserve /var/lib/liveswap /var/lib/hotserve-backup
# The package ships the Caddyfile here, so dpkg makes this directory —
# but this script also runs without the payload, and the backup
# settings and the timer marker below both live here. Root's, because
# the credentials do.
mkdir -p /etc/hotserve
chmod 755 /etc/hotserve
# Packages before the Debian-13-only matrix copied an AppArmor profile
# into /etc/apparmor.d (which the package itself does not own, so dpkg
# will not remove it on upgrade). Unload and delete it: apparmor.service
# parses that whole directory at every boot, and the wrapper it attached
# to is gone.
if [ -f /etc/apparmor.d/hotserve-user-manager ]; then
	if [ -d /sys/kernel/security/apparmor ] && command -v apparmor_parser >/dev/null 2>&1; then
		apparmor_parser -R /etc/apparmor.d/hotserve-user-manager 2>/dev/null || true
	fi
	rm -f /etc/apparmor.d/hotserve-user-manager
fi
if command -v systemctl >/dev/null 2>&1; then
	# liveswap runs deployed apps as transient units under the hotserve
	# user's own systemd manager (user@$uid.service), so they outlive
	# hotserve restarts and upgrades. Lingering keeps that manager
	# running with nobody logged in; the drop-in starts it alongside
	# hotserve and orders hotserve after it. No polkit and no root path:
	# hotserve talks to its own manager over /run/user/$uid.
	mkdir -p /etc/systemd/system/hotserve.service.d
	cat > /etc/systemd/system/hotserve.service.d/10-user-manager.conf <<EOF
# Generated by the hotserve package (postinstall); do not edit.
# liveswap's app units run under the hotserve user's manager.
[Unit]
Wants=user@$uid.service
After=user@$uid.service
EOF
	# The user manager's own limits are what its units inherit; match
	# hotserve.service so apps keep the file-descriptor headroom they
	# had as its children. (Effective from systemd 256, which is the
	# floor of the support matrix — see README.)
	mkdir -p "/etc/systemd/system/user@$uid.service.d"
	cat > "/etc/systemd/system/user@$uid.service.d/10-hotserve.conf" <<EOF
# Generated by the hotserve package (postinstall); do not edit.
[Service]
LimitNOFILE=1048576
EOF
	systemctl daemon-reload || true
	# Lingering starts user@$uid.service at once, so it comes after the
	# drop-ins above: the manager must be born with those limits. (An
	# already-running manager keeps them until it next starts —
	# restarting it would stop every app, which an upgrade must not do;
	# until then the sandbox probe reports what the running manager can
	# do.)
	loginctl enable-linger hotserve 2>/dev/null || {
		mkdir -p /var/lib/systemd/linger && touch /var/lib/systemd/linger/hotserve
	}
	systemctl try-restart hotserve 2>/dev/null || true
	# The backup timer is enabled but inert: its service refuses to
	# start until /etc/hotserve/backup.env exists, so an install turns
	# nothing on and configuring backups later needs no systemctl.
	# Enabling it here (rather than asking for it in the docs) is what
	# makes `hotserve backup init` the only step.
	#
	# Enabled once, then never touched again. "First install" is the
	# wrong test: dpkg passes the previously configured version as $2,
	# so a box upgrading from a hotserve that predates the timer would
	# skip this for ever — `hotserve backup init` would report the
	# repository ready and nothing would ever run. A marker records
	# that this package has enabled the timer once, so an operator who
	# then disables it — backups run from somewhere else, or a job was
	# hurting the box — keeps that choice across upgrades.
	#
	# It lives beside the backup credentials because that directory is
	# root's: the staging root is owned by the hotserve user, and a
	# compromised app must not be able to decide whether the next
	# upgrade turns backups on.
	timer_marker=/etc/hotserve/.backup-timer-configured
	if [ ! -e "$timer_marker" ]; then
		# The marker only once the enable has worked: written regardless,
		# one failed enable would stop every later upgrade from trying
		# again, and `hotserve backup init` would succeed on a box that
		# never runs a backup.
		if systemctl enable hotserve-backup.timer 2>/dev/null; then
			# touch, not `: > file`: a redirection that fails on a
			# special builtin ends a `set -e` shell whatever follows it,
			# and this script must not take the install down over a
			# marker.
			touch "$timer_marker" 2>/dev/null || true
		fi
		systemctl start hotserve-backup.timer 2>/dev/null || true
	fi
	echo "hotserve installed. Start it with:"
	echo "  sudo systemctl enable --now hotserve"
	# Only when it is true: an upgrade of a box whose backups work must
	# not be told they are off.
	if [ ! -e /etc/hotserve/backup.env ]; then
		echo "Backups are off until you run:"
		echo "  sudo hotserve backup init"
	fi
fi
