#!/bin/sh
set -e
if command -v useradd >/dev/null 2>&1; then
	getent group hotserve >/dev/null 2>&1 || groupadd --system hotserve
	getent passwd hotserve >/dev/null 2>&1 || useradd --system \
		--gid hotserve --home-dir /var/lib/hotserve \
		--shell /usr/sbin/nologin --comment "hotserve server" hotserve
else
	# Alpine (busybox) fallback.
	addgroup -S hotserve 2>/dev/null || true
	adduser -S -G hotserve -h /var/lib/hotserve -s /sbin/nologin hotserve 2>/dev/null || true
fi
if ! uid=$(id -u hotserve 2>/dev/null); then
	echo "hotserve: the hotserve system user does not exist and could not be created" >&2
	exit 1
fi
chown hotserve:hotserve /var/lib/hotserve /var/lib/liveswap
if command -v systemctl >/dev/null 2>&1; then
	# liveswap runs deployed apps as transient units under the hotserve
	# user's own systemd manager (user@$uid.service), so they outlive
	# hotserve restarts and upgrades. Lingering keeps that manager
	# running with nobody logged in; the drop-in starts it alongside
	# hotserve and orders hotserve after it. No polkit and no root path:
	# hotserve talks to its own manager over /run/user/$uid.
	mkdir -p /etc/systemd/system/hotserve.service.d
	cat > /etc/systemd/system/hotserve.service.d/10-user-manager.conf <<EOF
# Generated by the hotserve package (postinstall); do not edit.
# liveswap's app units run under the hotserve user's manager.
[Unit]
Wants=user@$uid.service
After=user@$uid.service
EOF
	# The user manager's own limits are what its units inherit; match
	# hotserve.service so apps keep the file-descriptor headroom they
	# had as its children.
	# ExecStart through the wrapper: the app sandbox is built on user
	# namespaces, which Ubuntu 24.04+ refuses to unconfined processes;
	# the shipped AppArmor profile attaches to the wrapper's path and
	# grants exactly that to exactly this manager (attachment by path
	# rather than AppArmorProfile=, which newer AppArmor turns into a
	# stack with "unconfined" for an unprivileged unit — still
	# restricted). Without AppArmor the wrapper is a plain exec.
	mkdir -p "/etc/systemd/system/user@$uid.service.d"
	cat > "/etc/systemd/system/user@$uid.service.d/10-hotserve.conf" <<EOF
# Generated by the hotserve package (postinstall); do not edit.
[Service]
LimitNOFILE=1048576
ExecStart=
ExecStart=/usr/libexec/hotserve/user-manager --user
EOF
	# Install the AppArmor profile into /etc/apparmor.d — which
	# apparmor.service parses in full at every boot — only where this
	# host's parser accepts it. The `userns` rule needs an AppArmor 4
	# parser; Debian 12 ships 3.x, which would reject the file and take
	# the whole policy load down with it, on a distro whose kernel does
	# not restrict user namespaces and therefore does not need the
	# profile at all. -Q parses without loading, so this is a real
	# compatibility test and not a guess at distro versions.
	src=/usr/share/hotserve/apparmor/hotserve-user-manager
	dst=/etc/apparmor.d/hotserve-user-manager
	if command -v apparmor_parser >/dev/null 2>&1 && [ -f "$src" ]; then
		if apparmor_parser -Q "$src" >/dev/null 2>&1; then
			install -m 0644 "$src" "$dst"
			# Load it now too; apparmor.service will reload it at boot.
			if [ -d /sys/kernel/security/apparmor ]; then
				apparmor_parser -r "$dst" 2>/dev/null \
					|| echo "hotserve: the hotserve-user-manager AppArmor profile could not be loaded; apps will run without the sandbox until it is" >&2
			fi
		else
			rm -f "$dst" # an upgrade from a package that installed it unconditionally
			echo "hotserve: this host's apparmor_parser does not support the profile hotserve ships (it needs AppArmor 4); not installing it — only kernels that restrict unprivileged user namespaces need it" >&2
		fi
	fi
	systemctl daemon-reload || true
	# Lingering starts user@$uid.service at once, so it comes after the
	# drop-ins above: the manager must be born with those limits and
	# under that profile. (An already-running manager keeps both until
	# it next starts — restarting it would stop every app, which an
	# upgrade must not do; until then the sandbox probe reports what the
	# running manager can do.)
	loginctl enable-linger hotserve 2>/dev/null || {
		mkdir -p /var/lib/systemd/linger && touch /var/lib/systemd/linger/hotserve
	}
	systemctl try-restart hotserve 2>/dev/null || true
	echo "hotserve installed. Start it with:"
	echo "  sudo systemctl enable --now hotserve"
fi
