#!/bin/sh
set -e
if command -v useradd >/dev/null 2>&1; then
	getent group hotserve >/dev/null 2>&1 || groupadd --system hotserve
	getent passwd hotserve >/dev/null 2>&1 || useradd --system \
		--gid hotserve --home-dir /var/lib/hotserve \
		--shell /usr/sbin/nologin --comment "hotserve server" hotserve
else
	# Alpine (busybox) fallback.
	addgroup -S hotserve 2>/dev/null || true
	adduser -S -G hotserve -h /var/lib/hotserve -s /sbin/nologin hotserve 2>/dev/null || true
fi
if ! uid=$(id -u hotserve 2>/dev/null); then
	echo "hotserve: the hotserve system user does not exist and could not be created" >&2
	exit 1
fi
chown hotserve:hotserve /var/lib/hotserve /var/lib/liveswap
if command -v systemctl >/dev/null 2>&1; then
	# liveswap runs deployed apps as transient units under the hotserve
	# user's own systemd manager (user@$uid.service), so they outlive
	# hotserve restarts and upgrades. Lingering keeps that manager
	# running with nobody logged in; the drop-in starts it alongside
	# hotserve and orders hotserve after it. No polkit and no root path:
	# hotserve talks to its own manager over /run/user/$uid.
	mkdir -p /etc/systemd/system/hotserve.service.d
	cat > /etc/systemd/system/hotserve.service.d/10-user-manager.conf <<EOF
# Generated by the hotserve package (postinstall); do not edit.
# liveswap's app units run under the hotserve user's manager.
[Unit]
Wants=user@$uid.service
After=user@$uid.service
EOF
	# The user manager's own limits are what its units inherit; match
	# hotserve.service so apps keep the file-descriptor headroom they
	# had as its children.
	# ExecStart through the wrapper: the app sandbox is built on user
	# namespaces, which Ubuntu 24.04+ refuses to unconfined processes;
	# the shipped AppArmor profile attaches to the wrapper's path and
	# grants exactly that to exactly this manager (attachment by path
	# rather than AppArmorProfile=, which newer AppArmor turns into a
	# stack with "unconfined" for an unprivileged unit — still
	# restricted). Without AppArmor the wrapper is a plain exec.
	mkdir -p "/etc/systemd/system/user@$uid.service.d"
	cat > "/etc/systemd/system/user@$uid.service.d/10-hotserve.conf" <<EOF
# Generated by the hotserve package (postinstall); do not edit.
[Service]
LimitNOFILE=1048576
ExecStart=
ExecStart=/usr/libexec/hotserve/user-manager --user
EOF
	# Load the profile into the running kernel now (apparmor.service
	# reloads /etc/apparmor.d on every boot). Best-effort: Debian 12's
	# AppArmor 3 parser cannot express the rule, and its kernel does
	# not need it.
	if [ -d /sys/kernel/security/apparmor ] && command -v apparmor_parser >/dev/null 2>&1; then
		apparmor_parser -r /etc/apparmor.d/hotserve-user-manager 2>/dev/null \
			|| echo "hotserve: could not load the hotserve-user-manager AppArmor profile (needed only where the kernel restricts unprivileged user namespaces)" >&2
	fi
	systemctl daemon-reload || true
	# Lingering starts user@$uid.service at once, so it comes after the
	# drop-ins above: the manager must be born with those limits and
	# under that profile. (An already-running manager keeps both until
	# it next starts — restarting it would stop every app, which an
	# upgrade must not do; until then the sandbox probe reports what the
	# running manager can do.)
	loginctl enable-linger hotserve 2>/dev/null || {
		mkdir -p /var/lib/systemd/linger && touch /var/lib/systemd/linger/hotserve
	}
	systemctl try-restart hotserve 2>/dev/null || true
	echo "hotserve installed. Start it with:"
	echo "  sudo systemctl enable --now hotserve"
fi
